spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # ?? ????? update, ?? ????? validate ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true # ??? ???? ???? ?? ???? ??? ? ???? ???? ??